fastlane_version "2.24.0"

default_platform :ios

lane :beta do
  sync_code_signing(type: "appstore")
  build_app(scheme: "JenkinsFastlaneExample",
            workspace: "JenkinsFastlaneExample.xcworkspace",
            include_bitcode: true)
end
